#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="torneiosm")]
	public partial class DB_TorneioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTime(Time instance);
    partial void UpdateTime(Time instance);
    partial void DeleteTime(Time instance);
    partial void InsertTorneio(Torneio instance);
    partial void UpdateTorneio(Torneio instance);
    partial void DeleteTorneio(Torneio instance);
    partial void InsertPartida(Partida instance);
    partial void UpdatePartida(Partida instance);
    partial void DeletePartida(Partida instance);
    #endregion
		
		public DB_TorneioDataContext() : 
				base(global::Data.Properties.Settings.Default.torneiosmConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_TorneioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_TorneioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_TorneioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_TorneioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Time> Times
		{
			get
			{
				return this.GetTable<Time>();
			}
		}
		
		public System.Data.Linq.Table<Torneio> Torneios
		{
			get
			{
				return this.GetTable<Torneio>();
			}
		}
		
		public System.Data.Linq.Table<Partida> Partidas
		{
			get
			{
				return this.GetTable<Partida>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Times")]
	public partial class Time : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    #endregion
		
		public Time()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Torneios")]
	public partial class Torneio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private EntitySet<Partida> _Partidas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    #endregion
		
		public Torneio()
		{
			this._Partidas = new EntitySet<Partida>(new Action<Partida>(this.attach_Partidas), new Action<Partida>(this.detach_Partidas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torneio_Partida", Storage="_Partidas", ThisKey="Id", OtherKey="TorneioId")]
		public EntitySet<Partida> Partidas
		{
			get
			{
				return this._Partidas;
			}
			set
			{
				this._Partidas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partidas(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Torneio = this;
		}
		
		private void detach_Partidas(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Torneio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Partidas")]
	public partial class Partida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _GolsTimeA;
		
		private System.Nullable<int> _GolsTimeB;
		
		private int _TorneioId;
		
		private int _TimeA;
		
		private int _TimeB;
		
		private System.Nullable<int> _Realizado;
		
		private EntityRef<Torneio> _Torneio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGolsTimeAChanging(System.Nullable<int> value);
    partial void OnGolsTimeAChanged();
    partial void OnGolsTimeBChanging(System.Nullable<int> value);
    partial void OnGolsTimeBChanged();
    partial void OnTorneioIdChanging(int value);
    partial void OnTorneioIdChanged();
    partial void OnTimeAChanging(int value);
    partial void OnTimeAChanged();
    partial void OnTimeBChanging(int value);
    partial void OnTimeBChanged();
    partial void OnRealizadoChanging(System.Nullable<int> value);
    partial void OnRealizadoChanged();
    #endregion
		
		public Partida()
		{
			this._Torneio = default(EntityRef<Torneio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GolsTimeA", DbType="Int")]
		public System.Nullable<int> GolsTimeA
		{
			get
			{
				return this._GolsTimeA;
			}
			set
			{
				if ((this._GolsTimeA != value))
				{
					this.OnGolsTimeAChanging(value);
					this.SendPropertyChanging();
					this._GolsTimeA = value;
					this.SendPropertyChanged("GolsTimeA");
					this.OnGolsTimeAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GolsTimeB", DbType="Int")]
		public System.Nullable<int> GolsTimeB
		{
			get
			{
				return this._GolsTimeB;
			}
			set
			{
				if ((this._GolsTimeB != value))
				{
					this.OnGolsTimeBChanging(value);
					this.SendPropertyChanging();
					this._GolsTimeB = value;
					this.SendPropertyChanged("GolsTimeB");
					this.OnGolsTimeBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TorneioId", DbType="Int NOT NULL")]
		public int TorneioId
		{
			get
			{
				return this._TorneioId;
			}
			set
			{
				if ((this._TorneioId != value))
				{
					if (this._Torneio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTorneioIdChanging(value);
					this.SendPropertyChanging();
					this._TorneioId = value;
					this.SendPropertyChanged("TorneioId");
					this.OnTorneioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeA", DbType="Int NOT NULL")]
		public int TimeA
		{
			get
			{
				return this._TimeA;
			}
			set
			{
				if ((this._TimeA != value))
				{
					this.OnTimeAChanging(value);
					this.SendPropertyChanging();
					this._TimeA = value;
					this.SendPropertyChanged("TimeA");
					this.OnTimeAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeB", DbType="Int NOT NULL")]
		public int TimeB
		{
			get
			{
				return this._TimeB;
			}
			set
			{
				if ((this._TimeB != value))
				{
					this.OnTimeBChanging(value);
					this.SendPropertyChanging();
					this._TimeB = value;
					this.SendPropertyChanged("TimeB");
					this.OnTimeBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Realizado", DbType="Int")]
		public System.Nullable<int> Realizado
		{
			get
			{
				return this._Realizado;
			}
			set
			{
				if ((this._Realizado != value))
				{
					this.OnRealizadoChanging(value);
					this.SendPropertyChanging();
					this._Realizado = value;
					this.SendPropertyChanged("Realizado");
					this.OnRealizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torneio_Partida", Storage="_Torneio", ThisKey="TorneioId", OtherKey="Id", IsForeignKey=true)]
		public Torneio Torneio
		{
			get
			{
				return this._Torneio.Entity;
			}
			set
			{
				Torneio previousValue = this._Torneio.Entity;
				if (((previousValue != value) 
							|| (this._Torneio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Torneio.Entity = null;
						previousValue.Partidas.Remove(this);
					}
					this._Torneio.Entity = value;
					if ((value != null))
					{
						value.Partidas.Add(this);
						this._TorneioId = value.Id;
					}
					else
					{
						this._TorneioId = default(int);
					}
					this.SendPropertyChanged("Torneio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
